---
language: python

python:
  - 3.6

env:
    - ROLE=direnv
    - ROLE=git
    - ROLE=i3
    - ROLE=pipenv
    - ROLE=stack
# TODO: when Mazer and new Ansible are stable, parametrize versions here
#   - ANSIBLE_VERSION=latest
#   - ANSIBLE_VERSION=2.4.0

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip
    # molecule/ansible requirement https://github.com/ansible/ansible/issues/34340
    - libssl-dev

install:
  # TODO: see env:
  # - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run bash -c "(cd roles/\${ROLE}; molecule test)"
