---
- name: install system Python 3 and pip in RedHat Family
  dnf:
    name: ['python3', 'python3-pip']
    state: present
    update_cache: true
  become: true

- name: "Upgrade pip3 on user folder in RedHat Family"
  pip:
    name: pip
    executable: pip3
    state: present
    extra_args: -U --user
