---
- name: Add Mozilla apt repo GPG public key.
  apt_key:
    data: "{{ firefox_ubuntu_ppa_apt_key_content }}"
    state: present

- name: Add Mozilla Daily apt repo for Firefox.
  become: yes
  apt_repository:
    repo: "{{ firefox_ubuntu_ppa }}"
    state: present

- name: Install Firefox.
  become: yes
  apt:
    name: firefox
    state: present
