---
- name: Download Firefox tarball.
  get_url:
    url: "{{ firefox_download_url }}"
    dest: "{{ firefox_download_directory }}/{{ firefox_download_tarball }}"

- name: Create Firefox install directory.
  file:
    path: "{{ firefox_install_directory }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Extract Firefox tarball.
  unarchive:
    src: "{{ firefox_download_directory }}/{{ firefox_download_tarball }}"
    dest: "{{ firefox_install_directory }}"
    copy: no
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Create symlink for Firefox binary.
  block:
    - name: Create directory for binary shortcuts
      file:
        path: "{{ firefox_symlink_dest_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"
    - name: Create actual symlink
      file:
        state: link
        src: "{{ firefox_symlink_src }}"
        dest: "{{ firefox_symlink_dest }}"
  when: firefox_create_symlink == true

- name: Create desktop shortcut
  block:
    - name: Create directory for destop shortcuts
      file:
        path: "{{ firefox_desktop_shortcut_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"
    - name: Create actual desktop shortcut
      template:
        dest: "{{ firefox_desktop_shortcut }}"
        src: firefox-developer-edition.desktop.j2
        mode: "u=rw,g=r,o=r"
        owner: "{{ user }}"
        group: "{{ user }}"
