---
# tasks file for firefox

- include: install_from_ppa.yml
  when: ansible_distribution == 'Ubuntu'

- include: install_from_tarball.yml
  when: false

- include: install_from_unstable.yml
  when: ansible_distribution == 'Debian'
